name: Replace Server Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    strategy:
      matrix:
        node-version: [18.x] 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
      
      - name: Create .env file
        run: |
          echo GOOGLE_MAP_KEY=${{ secrets.GOOGLE_MAP_KEY }} >> .env

      - name: Build Angular app
        run: npm run build-prod
      
      - name: List build directory
        run: ls -alh dist/

      - name: Upload production-ready build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: dist/

  replace_build_content:
    runs-on: ubuntu-latest
    needs: build
    environment: production

    steps:

      - name: List build directory before SCP
        run: ls -alh dist/

      - name: Connect to server and copy source code
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_PASSWORD }}
          source: "dist/*"
          target: "~/active/"

      - name: Connect to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cp -r ~/active/dist/* /var/www/apps/active/


# name: Replace Server Build

# on:
#   push:
#     branches:
#       - master

# jobs:
#   copy_build_to_server:
#     runs-on: ubuntu-latest
#     environment: production

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Install sshpass and ssh-agent
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y sshpass openssh-client

#       - name: Start SSH agent
#         id: ssh-agent-setup
#         run: |
#           eval "$(ssh-agent -s)"
#           echo "$SSH_PRIVATE_KEY" > private_key
#           chmod 600 private_key
#           sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh-add private_key
#         env:
#           SSH_PASSPHRASE: ${{ secrets.SERVER_PASSWORD }}
#           SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}

#       - name: Add GitHub to known hosts
#         run: |
#           mkdir -p ~/.ssh
#           ssh-keyscan github.com >> ~/.ssh/known_hosts

#       - name: Copy source code with rsync
#         uses: appleboy/ssh-action@v0.1.3
#         with:
#           host: ${{ secrets.SERVER_HOST }}
#           username: ${{ secrets.SERVER_USERNAME }}
#           key: ${{ secrets.SERVER_SSH_KEY }}
#           passphrase: ${{ secrets.SERVER_PASSWORD }}
#           script: |
#             rsync -avz --delete --exclude='.git*' ./dist/browser/ /var/www/apps/active/